[package]
name = "dialectic"
version = "0.1.0"
authors = ["Kenny Foner <kwf@very.science>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
thiserror = "1"
tokio = { version = "0.3", features = ["sync"] }
call-by = { version = "0.1", path = "../call-by" }

[dev-dependencies]
tokio = { version = "0.3", features = ["full"] }