[workspace]
members = [
    "dialectic",
    "dialectic-compiler",
    "dialectic-macro",
    "dialectic-null",
    "dialectic-retry",
    "dialectic-tokio-mpsc",
    "dialectic-tokio-serde",
    "dialectic-tokio-serde-bincode",
    "dialectic-tokio-serde-json",
]