[package]
name = "dialectic-macro"
version = "0.1.0"
authors = ["Sean Leffler <sean@errno.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
dialectic-compiler = { path = "../dialectic-compiler" }
syn = "1.0.60"
proc-macro2 = "1.0.24"
