[package]
name = "dialectic-macro"
version = "0.1.0"
authors = ["Sean Leffler <sean@errno.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
dialectic-compiler = { path = "../dialectic-compiler" }
syn = { version = "1.0", features = ["full", "parsing"] }
proc-macro2 = "1.0"
quote = "1.0"
proc-macro-crate = "0.1.5"
lazy_static = "1.4.0"

[dev-dependencies]
dialectic = { path = "../dialectic" }
static_assertions = "1.1"
tokio = "1.2.0"
