[package]
name = "dialectic-compiler"
version = "0.1.0"
authors = ["Sean Leffler <sean@errno.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thunderdome = "0.4.0"
syn = { version = "1.0.60", features = ["full"] }
proc-macro2 = "1.0.24"
quote = "1.0.9"
