[package]
name = "dialectic-compiler"
version = "0.1.0"
authors = ["Sean Leffler <sean@errno.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thunderdome = "0.4"
syn = { version = "1.0", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
quote = "1.0"
proc-macro-crate = "0.1"
lazy_static = "1.4"
thiserror = "1.0"
quickcheck = "1.0"
