name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        components: rustfmt, clippy
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Format check
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --all-features --all-targets --verbose
    - name: Clippy lint
      run: cargo clippy --all-features --all-targets --verbose -- -Dwarnings
    - name: Run all tests except doctests
      run: cargo test --all-features --all-targets --verbose
    - name: Run all doctests
      run: cargo test --all-features --doc --verbose
    - name: Build documentation
      run: cargo doc --all-features --verbose
