name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all-features --all-targets --verbose -- -Dwarnings
    - name: Clippy lint
      run: cargo clippy --all-features --all-targets --verbose -- -Dwarnings
    - name: Run tests
      run: cargo test --all-features --all-targets --verbose -- -Dwarnings
    - name: Build documentation
      run: cargo doc --all-features --all-targets --verbose -- -Dwarnings
