name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all-features --verbose
    - name: Clippy lint
      run: cargo clippy --all-features --verbose -- -Dwarnings
    - name: Run tests
      run: cargo test --all-features --verbose
    - name: Build examples
      run: cargo build --all-features --verbose --examples
    - name: Build documentation
      run: cargo doc --all-features --verbose
    - name: Build documentation in docs.rs mode
      run: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
