name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        components: rustfmt, clippy
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features --all-targets --verbose
    - name: Clippy lint
      run: cargo clippy --all-features --all-targets --verbose -- -Dwarnings
    - name: Run tests
      run: cargo test --all-features --all-targets --verbose
    - name: Build documentation
      run: cargo doc --all-features --verbose
